name: update-collection

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the action
  workflow_dispatch:

jobs:
  update-collection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # specify the PHP version

    - name: Create config.php
      run: |
        mkdir -p docs/updater
        echo '<?php' > docs/updater/config.php
        echo '// Configuration' >> docs/updater/config.php
        echo "\$server = 'https://raw.githubusercontent.com/';" >> docs/updater/config.php
        echo "\$repopath = 'eried/ArduboyCollection/'; // Source repository" >> docs/updater/config.php
        echo '' >> docs/updater/config.php
        echo '// Github credentials' >> docs/updater/config.php
        echo "\$client_id='${{ secrets.CLIENT_ID }}';" >> docs/updater/config.php
        echo "\$client_secret='${{ secrets.CLIENT_SECRET }}';" >> docs/updater/config.php

    - name: Execute update.php
      run: php docs/updater/update.php

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/repo.json
        git add docs/index.html
        git reset docs/updater/config.php  # Exclude config.php from the commit
        git commit -m "Repo update" -a || echo "No changes to commit"
        git push
